### ISSUE TITLE
Vertices without edges are ignored by motionpaste

### ISSUE THREAD

**Issue by hollunder** [dalboris/vpaint#76] opened 2017-01-19 11:34 UTC
Hi there,

I just started experimenting with vpaint and intend to use it for some simple things, if I manage to figure stuff out that is.

Anyway, this is about a bug where motionpaint ignores vertices, see attached 3 frame animation.

![vertex_bug](https://cloud.githubusercontent.com/assets/8207622/22105265/796dfd34-de43-11e6-8c86-13281aeedcc0.gif)

**Comment by dalboris** [comment] 2017-01-20 05:18
Can you explicit a bit more the problem? For instance, what are the exact steps that you followed, so that I can try to reproduce it on my side.

**Comment by hollunder** [comment] 2017-01-20 08:49
Quite simple:
1) Draw something that includes vertices without edges.
2) Motionpaste it.

See attached file. (Had to zip it for github)


[vertex_bug.vec.zip](https://github.com/dalboris/vpaint/files/718846/vertex_bug.vec.zip)

**Comment by dalboris** [comment] 2017-01-20 17:57
Thx, I'll have a look alter.

**Comment by dalboris** [comment] 2019-11-15 20:57
This is now fixed for upcoming VPaint 1.7!

Note that by design, VPaint doesn't allow you to draw isolated vertices. What you had drawn were in fact very tiny closed edges (=loops). However, there was indeed a bug: those tiny closed edges were not interpolated correctly (they were so small that VPaint didn't generate enough samples), so you couldn't see the interpolation. This bug is fixed, and your example now renders correctly. :)

**Closed by dalboris** 2019-11-15 20:57 UTC
