### ISSUE TITLE
The drawing dot/circle freeze.

### ISSUE THREAD

**Issue by ebarranco** [dalboris/vpaint#103] opened 2018-12-08 00:25 UTC
When I use the sketch tool the drawing dot/circle icon freeze at the end of every stroke and it doesn't follow the cursor anymore.  [I show you the behavior here.](https://www.dropbox.com/s/jo0dl0umiuhanf0/2018-12-07%2018-04-09.mov?dl=0)

**Comment by ebarranco** [comment] 2018-12-08 03:36
Working a little more with vpaint, the same happened with the sculpt tool, the circle stay on the  last line, not follow the cursor and  just appear when I try to modified other line.

**Comment by ebarranco** [comment] 2018-12-08 16:03
I think about the last changes because a did a video a day before. If you watch my previous issue about the background you can see the sketch tool works normally, either way[ here I show you side by side both versions and the differences that I see now with the sketch and sculpt tool.](https://www.dropbox.com/s/k15legho7qqof4w/2018-12-08%2009-46-53.mov?dl=0)

**Comment by dalboris** [comment] 2018-12-08 16:19
Thanks a lot for the videos, that's definitely a really big problem, not subtle at all :) Can you explicitly clarify what commit SHA1 is the build of the left-side VPaint, and what commit SHA1 is the build of the right-side VPaint? I may be wrong, but I'd be surprised if any of the last two commits (6a4dac0, 8b4b63c) could create such a regression.

**Comment by ebarranco** [comment] 2018-12-08 16:37
I don't even now what SHA1 is... sorry :S the version to the left is vpaint-1-6-linux-64bit from here github releases.  The right version is from my  arch repositories [vpaint-git](https://aur.archlinux.org/packages/vpaint-git/) when you commit a change, my package manager notify me and I just update.

**Comment by dalboris** [comment] 2018-12-08 16:42
Ah, ok, the left side is VPaint 1.6, I didn' t realize the lack of layers :)

The "SHA1", or "hash" of a commit is basically its name. It is the number you can see here on the right of its commit in the git history:

https://github.com/dalboris/vpaint/commits/master

I do not know how Arch repository work: do you know if it is possible to compile at a specific commit, instead of the latest one?

**Comment by ebarranco** [comment] 2018-12-08 18:04
It seems that it's possible to do that but I can't really understand much. Give me a day to learn git and I'll back with the info.

**Comment by ebarranco** [comment] 2018-12-08 18:10
@dalboris I was wondering why you can't reproduce it, and suddenly I couldn't either. It was because I try it with my mouse, the bug only shows when I'm using my Wacom tablet. With my mouse works as expected.

**Comment by ebarranco** [comment] 2018-12-08 18:55
Wacom Bamboo  Pen and Touch Tablet (CTH670)

**Comment by dalboris** [comment] 2018-12-08 19:14
Ok thanks! And good news: I managed to reproduce the problem by compiling against Qt 5.11.2 instead of Qt 5.12 :) This means:
1. The problem should fix itself once you upgrade to Qt 5.12, and
2. I can make some tests and try to fix the problem for Qt 5.11 (not today). No need for any more work on your side.

**Comment by ebarranco** [comment] 2018-12-08 19:33
Ok, I was just building direct from git the different commits. I know how to do it now. :+1:  Maybe will help for future reports :)

**Comment by dalboris** [comment] 2018-12-08 19:53
Great, congratulations!! This may come in handy in the future yes :) Did 
you manually download Qt from https://www.qt.io, or did you use a Qt 
version packaged by Arch? If you do it manually, you should be able to 
build against Qt 5.12 and get rid of the bug right now.

**Comment by ebarranco** [comment] 2018-12-08 19:59
I used my OS version 5.11.2-3. But I'm downloading the last version from the page but is a really big download. I'll use that and make you know the result.

**Comment by dalboris** [comment] 2018-12-08 20:06
Yes, those are big downloads and it takes a little while to install. For info, I usually download the web installer, and then only install the "Desktop gcc 64-bit" module of the Qt version I'm interested in:

![qt-maintenance-tool](https://user-images.githubusercontent.com/4809739/49690196-032a3d00-fb2d-11e8-8821-16d6891522cb.png)

VPaint doesn't depend on any other modules.

**Comment by dalboris** [comment] 2018-12-08 20:08
And once you've done the process at least once, you can install additional ones via the "maintenance tool": `~/Qt/MaintenanceTool`

**Comment by ebarranco** [comment] 2018-12-08 20:09
Ok, I'll do that way.

**Comment by ebarranco** [comment] 2018-12-08 21:00
I finish to compile @dalboris and [it works look!](https://www.dropbox.com/s/6zi0swoqjsnnq9h/2018-12-08%2014-51-35.mov?dl=0) Today I learned a lot of useful things, thanks.

**Comment by dalboris** [comment] 2018-12-09 09:34
Awesome, great news! :) I'll close this issue then, since I'm planning to release VPaint 1.7 as an AppImage with Qt 5.12.

**Closed by dalboris** 2018-12-09 09:34 UTC
Labels: bug
