### ISSUE TITLE
Interpolation pitfalls

### ISSUE THREAD

**Issue by SpooikypokDev** [dalboris/vpaint#72] opened 2016-12-01 21:13 UTC
The "action and reaction" interpolation effect should either have an option for better control (aka tween control), or be fixed if it is a bug. It gives an "alive" effect on tweens, but sometimes it is not desirable. And the way it works is hardly predictable. I made an animation, and the mouth swings like miley cyrus after a move while the eyes are normal after making the same movement!

**Comment by dalboris** [comment] 2016-12-04 01:39
Yep, very definitely! This is a known current limitation of VPaint which makes it currently unusable for any serious animation. There will be more control in the future. I close as duplicate of #41.

**Closed by dalboris** 2016-12-04 01:39 UTC
