### ISSUE TITLE
Keyframe selection change the order of elements

### ISSUE THREAD

**Issue by ebarranco** [dalboris/vpaint#107] opened 2019-10-14 16:11 UTC
Vpaint - Master
OS - Linux

Issue:
Using Keyframe selection (k) changes the order of drawings when you are working with more of two elements.

Steps:
1. Draw three circles of different size or color and stack them in particular order
2. Select the drawings and Motion Copy/Paste
3. Add a in-between with keyframe selection
4. The order of the drawings has changed.

**Comment by dalboris** [comment] 2019-10-15 16:00
Good catch! I definitely forgot to think about depth ordering when keyframing. This should be interesting to fix, and the solution will be directly useful for VGC too, so I'll clearly spend the time to fix for VPaint 1.7.

More minimal/detailed example:
1. Draw an edge E1
2. Draw an overlapping edge E2 on top (e.g., with auto-intersections disabled)
4. Select E1 and stack it above E2 with PageUp
5. Select All and copy-motion-paste to another frame
6. Add an inbetween frame

**Comment by ebarranco** [comment] 2019-10-15 16:14
Great! Originally found the problem just with edges but took me a long time to figure it out what was happening so I thought the use of faces and colors was more clear to report the issue.

**Comment by dalboris** [comment] 2019-10-15 16:16
Absolutely, using colors or faces definitely help to "see" the depth-ordering problem :)

**Comment by dalboris** [comment] 2019-10-17 13:34
Alright, it turns out I did not completely forgot to think about depth ordering when keyframing, but got it wrong. It should be fixed now, and was actually easier to fix than I thought :)

Let me know if it seems to work for you, and by the way, also let me know if you see any performance regressions since my fix for #105.

**Closed by dalboris** 2019-10-17 13:34 UTC

**Comment by ebarranco** [comment] 2019-10-17 19:40
I'm glad to read that, it works pretty well! I don't notice any change in performance, I'll continue testing and let you know if behaves otherwise.

**Comment by dalboris** [comment] 2019-10-18 08:43
Great, thanks! :)
