### ISSUE TITLE
VPaint crashes when face cycles is empty

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#59] opened 2016-03-17 05:28 UTC
The title pretty much sums it up. The error is an out of bounds error from QList. Here is the contents of a vec file that can replicate this bug:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with VPaint (http://www.vpaint.org) -->

<vec
  version="1.6">
  <playback
    framerange="0 47"
    fps="24"
    subframeinbetweening="off"
    playmode="normal"/>
  <canvas
    position="0 0"
    size="1280 720"/>
  <layer>
    <background
      color="rgba(255,255,255,1)"
      image=""
      position="0 0"
      size="cover"
      repeat="norepeat"
      opacity="1"
      hold="yes"/>
    <objects>
      <face
        id="99"
        cycles="[]"
        color="rgba(127,255,212,1)"/>
    </objects>
  </layer>
</vec>
```

**Comment by dalboris** [comment] 2016-03-17 08:03
Thx for reporting! I won't have a look anytime soon (say, the following 2/3 weeks), but I will eventually :-)

**Comment by dalboris** [comment] 2019-11-15 12:52
Looking at this. As I said, "I will eventually" ;-)

**Comment by dalboris** [comment] 2019-11-15 13:36
Ok, so in fact, such *.vec file is invalid and is not supposed to be readable by VPaint. Do you remember if you encountered this bug on a file generated by VPaint, or only on files written by hand outside of VPaint?

In the mathematical definition of a vector graphics complex, there is no such thing as an "empty cycle".

However, each face may have 0, 1, or several cycles defining its boundary. In *.vec syntax (which is admittedly weird and confusing... my bad), specifying the cycles look like this:

```
cycles = "[ ... cycle 1 ... ] [ ... cycle 2 ... ] ..."
```

So a face with zero cycles in its boundary must be specified like this:

```
cycles = ""
```

NOT like this:

```
cycles = "[]"
```

The latter would mean "one cycle defined by []", but the string "[]" isn't a valid cycle, since there is no such thing as an empty cycle.

Currently, generating faces with zero cycles from VPaint isn't easy (by design), but can be done via:
- Draw a closed edge.
- Fill with a color. This gives you a "disk": a face with one cycle, made of one closed edge.
- Copy-paste the disk
- Glue the boundary of the first and second disks together. It will look like a single disk, but it's actually two disks sharing a common boundary, stacked on top of each others.
- Select all and use the simplification operator (backspace). This creates a topological sphere, that is, a 2-manifold without boundary of genus zero. It can't be rendered on VPaint so you won't see anything on screen, but if you save the file it does the correct thing:

```
<face
        id="8"
        cycles=""
        color="rgba(0,85,255,1)"/>
```

I'm closing this, but feel free to reopen if you find that VPaint does generate files containing `cycles="[]"`, which it shouldn't.

**Closed by dalboris** 2019-11-15 13:36 UTC
Labels: bug

**Comment by scribblemaniac** [comment] 2019-11-15 23:28
This was way too long ago for me to remember the details of this, but I'm pretty sure I only would have reported this if VPaint had created a file with `cycles="[]"`. At any rate, invalid cycles should be handled gracefully and not crash the program.

**Comment by dalboris** [comment] 2019-11-16 00:16
There are different school of thoughts about that, but yes, I'm in the camp that thinks that ideally, VPaint should handle this invalid files gracefully. It just makes it not a bug, just a feature request, and with lower priority ;-) The bug would be why this invalid face was generated in the first place.
